title: Inktober 2019
email: rickinbsb@gmail.com
description: Artes do Inktober 2019 feitas pelos membros do grupo Batatinha quando nasce
baseurl: "/"
url: "https://rickinbsb.github.io/inkfritas2019"
twitter_username: rickinbsb
github_username:  rickinbsb
theme: minima
plugins:
  - jekyll-feed